services:
  zookeeper:
    image: zookeeper:3.8.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    restart: on-failure
    #network_mode: host  # Использует сетевой стек хоста
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_DIRS: /kafka-logs
      KAFKA_NUM_IO_THREADS: 8 #число потоков ввода-вывода, по одному на каждый каталог из log.dirs
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_NUM_PARTITIONS: 3  # число разделов при создании темы
      KAFKA_LOG_RETENTION_MS: 259200000 # время хранения сообщений (3 дня)
      KAFKA_LOG_RETENTION_BYTES: 10737418240  # максимальный размер лога одного раздела (10 GB)
      KAFKA_LOG_SEGMENT_BYTES: 134217728   # размер одного сегмента лога (128 MB)
      KAFKA_LOG_SEGMENT_MS: 3600000    # ротация сегмента по времени (1 час)
      KAFKA_MESSAGE_MAX_BYTES: 5242880   # максимальный размер одного сообщения (5 MB)
      KAFKA_BATCH_SIZE: 0   # максимальный размер batch в байтах.
      KAFKA_LINGER_MS: 500   # время, которое продюсер ждёт перед отправкой неполного batch
    command: ["sh", "-c", "mkdir -p /kafka-logs && chown -R 1000:1000 /kafka-logs && /etc/confluent/docker/run"]
    user: root
    #volumes:  #снаружи контейнера
    #  - /c/Kafka/KafkaLogs:/kafka-logs
    depends_on:
      - zookeeper

#  control-center:
#    image: confluentinc/cp-control-center:latest
#    ports:
#      - "9021:9021"
#    environment:
#      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
#      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
#      CONTROL_CENTER_ZOOKEEPER: zookeeper:2181
#      CONTROL_CENTER_REPLICATION_FACTOR: 1
#      CONTROL_CENTER_PORT: 9021
#    depends_on:
#      - kafka
#      - zookeeper

#volumes: #снаружи контейнера
#  kafka-data: