server:
  port: 8882
  servlet:
    context-path: /kafka-course/api/v1
  error:
    include-message: always
spring:
  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      group-id: "my-consumer-group"
      auto-offset-reset: "earliest"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.apache.kafka.common.serialization.StringSerializer"
    task-topic: "tasks"
    message-topic: "messages"
    message-event-topic: "message-events"
