server:
  port: 8882
  servlet:
    context-path: /kafka-course/api/v1
  error:
    include-message: always
spring:
  application:
    name: kafka-course
  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      group-id: "my-consumer-group"
      auto-offset-reset: "earliest"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    producer:
      retries: 3
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      enable-idempotence: "true"
      acks: "all"
    task-topic: "tasks"
    message-topic: "messages"
    message-event-topic: "message-events"

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/kafka_course_db?authSource=admin&retryWrites=false
